# Numpy 

1. Numpy stands for numerical python
2. Works to resolve the array 
3. Array is a data structure used for     storing numerical values
4. Faster and more memory efficient
5. Used for BroadCasting
6. Ideal for Scientific computing and ML 

In [4]:
! pip install numpy 

In [1]:
import numpy as np 

In [128]:
arr0 = np.array(32)
print(arr0) 
print(arr0.ndim)

32
0


In [7]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.ndim)

[1 2 3 4 5]
1


In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)                          
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [9]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3[1,1,2])

12


In [10]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[1,2])

6


In [18]:
#Slicing
arr1 = np.array([1,2,3,4,5])
print(arr1[0:2])


[1 2]


In [19]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[1 , 0:])

[4 5 6]


In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3[0,1,0:1])                                                                                     

[4]


In [21]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.shape)    

(2, 3)


In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(arr3.shape) 

(2, 2, 3)


In [ ]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])  # 1x12 , 12x1 , 2x6 , 6x2 , 3x4 , 4x3
new_a1 = a1.reshape(1,12)   
print(new_a1) 
print(a1.ndim)
print(new_a1.ndim)                              

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
1
2


In [ ]:
a1 = np.array([1,2,3,4,5,6,7,8])  #2x2x2 , #1x8x1
new_a1 = a1.reshape(8,1,1) 
print(new_a1)                                                    
            

[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]]


In [4]:
x = []

for i in range(1,5):
    int_1 = int(input("Enter: "))
    x.append(int_1)

print(x)

[1, 2, 3, 4]


In [6]:
import numpy as np 
arr = np.array([1,2,3,4] , ndmin = 10)
print(arr) 
print(arr.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [8]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
arr = np.array([1,2,3,4] , ndmin = 5)
print(arr)
print(arr.ndim) 

[[[[[1 2 3 4]]]]]
5


In [10]:
arr = np.zeros(4)
print(arr) 

[0. 0. 0. 0.]


In [26]:
arr = np.ones(5) 
print(arr)

[1. 1. 1. 1. 1.]


In [28]:
arr = np.empty(8)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.arange(5)
print(arr) 

[0 1 2 3 4]


In [ ]:
# Creating Square matrix 
arr_dia = np.eye(4)
print(arr_dia) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Diagonal 

In [ ]:
# For creating the diagonal matrix
arr_dia = np.eye(3,5) 
print(arr_dia) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### Linspace

In [42]:
ar_lin = np.linspace(1 , 10 , num = 5)  
print(ar_lin) 

[ 1.    3.25  5.5   7.75 10.  ]


### Random 

1. rand() - generate a random value between 0 and 1
2. randn() - generate a random value close to zero
3. ranf() - generates a value between 0 and 1 but 0 included

In [46]:
var = np.random.rand(4) 
print(var) 

[0.21688439 0.32793032 0.23290557 0.41345481]


In [53]:
var1 = np.random.rand(2,2) 
print(var1)
print(var1.ndim)  

[[0.72491455 0.68773611]
 [0.14423077 0.3936523 ]]
2


In [54]:
var2 = np.random.rand(3,3) 
print(var2) 

[[0.92910306 0.23705517 0.98586273]
 [0.65989267 0.47884184 0.4796693 ]
 [0.89479262 0.03833865 0.87372708]]


### randn() 

In [55]:
x = np.random.randn(5)
print(x) 

[ 1.01134177  0.70382213 -0.9213227  -0.88844861  0.075113  ]


### ranf()

In [3]:
import numpy as np 
y = np.random.ranf(5) 
print(y) 

[0.0121589  0.03679143 0.81689897 0.71322243 0.9868476 ]


### randint()

In [1]:
# np.random.randint(min , max , total_values) 
import numpy as np 
z = np.random.randint(4 , 15 , 6) 
print(z) 

[14  8  4 10 12  4]


### Datatypes in Numpy

List of Characters used to identify datatype

1. **i -  integer**
2. **b -  boolean**
3. **u -  unsigned integer**
4. **f -  float**
5. **c -  complex float**
6. **m -  timedelta**
7. **M -  datetime**
8. **O -  object**
9. **S -  string**
10. **U - Unicode string**
11. **V - the fixed chunk of memory for other types (void)** 

In [19]:
var = np.array([128, 1, 2,3 , 4])
print("Datatype: ",var.dtype)

Datatype:  int64


In [3]:
import numpy as np 

In [6]:
z = np.array([-128 , 0 , 127] , dtype = 'int32') 
print(z.dtype)  

int32


In [ ]:
var = np.array(["a" , "b" , "c" , "d"]) 
print(var.dtype) 

<U1


In [27]:
var = np.array(["a" , "b" , "c" , "d" , 1 , 2 , 3 , 4 ]) 
print(var.dtype) 

<U21


In [30]:
var = np.array(["A" , "B" , "C" , "D" ,1.1 , 2.2 , 3.3 , 4.4 , 2 , 4]) 
print(var.dtype) 

<U32


In [31]:
var = np.array([1,2,3,4,5] , dtype = np.int8)
print(var.dtype) 

int8


In [32]:
var = np.array([1,2,3,4] , dtype = np.int32)
print(var.dtype) 

int32


In [33]:
var = np.array([1,2,3,4] , dtype = "f")
print(var.dtype)

float32


In [35]:
#conversion 

x1 = np.array([1,2,3,4,5])

float_conversion = np.float32(x1)

int_conversion = np.int_(float_conversion) 

print("Float_Conversion: " , float_conversion)
print("int_conversion: " , int_conversion) 

Float_Conversion:  [1. 2. 3. 4. 5.]
int_conversion:  [1 2 3 4 5]


### Arithmetic Operation

1. add - np.add(a,b) 
2. subtract - np.subtract(a,b) 
3. multiply - np.multiply(a,b) 
4. divide - np.divide(a,b) 
5. mod - np.mod(a,b) 
6. power - np.power(a,b) 
7. reciprocal - np.reciprocal(a,b) 

In [38]:
a = np.array([1,2,3,4]) 

b = np.array([5,4,3,2]) 

a1 = a + 4
b1 = b + 3
x = np.add(a,b)
print(x) 
print(a1)
print(b1) 

[6 6 6 6]
[5 6 7 8]
[8 7 6 5]


In [39]:
x1 = np.array([1,2,3,8]) 
x2 = np.array([4,3,7,2]) 

x_new = np.reciprocal(x1 , x2) 
print(x_new) 

[1 0 0 0]


In [40]:
var1 = np.array([1,2,3,13]) 
var2 = np.array([1,2,3,11]) 
var_new = np.divide(var1 , var2) 
print(var_new) 

[1.         1.         1.         1.18181818]


In [ ]:
#2D array
x = np.array([[1,2,3,4,5] , [1,2,3,4,5]])
y = np.array([[5,4,3,2,1] , [6,7,8,9,10]])

print(x) 
print() 
print(y)
print()
new_var = np.add(x , y) 
print(new_var) 

[[1 2 3 4 5]
 [1 2 3 4 5]]

[[ 5  4  3  2  1]
 [ 6  7  8  9 10]]

[[ 6  6  6  6  6]
 [ 7  9 11 13 15]]


### Arithmetic Functions

1. np.min() - defines the minimum value
2. np.max() - defines the maximum value
3. np.argmin(x) - position of the minimum value
4. np.sqrt() - square root
5. np.sin() - sin function 
6. np.cos() - cos function 
7. np.cumsum() 

In [46]:
x = np.array([1,2,3,4]) 
y = np.array([4,3,2,1]) 

var = np.array([12,13,14,15]) 

x1 = np.min(var)
x_1 = np.argmin(var) 
print(x1 , x_1)          
print()           

x2 = np.max(var)
x_2 = np.argmax(var) 
print(x2 , x_2)                               


12 0

15 3


In [ ]:
# 2D array (axis = 0 columns) & (axis = 1 rows)
var1 = np.array([[1,2,3] , [4,5,6]]) 

print(np.min(var1 , axis = 0)) 
print(np.min(var1 , axis = 1))
print(np.min(var1 , axis = 0))  
print(np.max(var1 , axis = 1))

[1 2 3]
[1 4]
[1 2 3]
[3 6]


In [ ]:
var2 = np.array([1,2,3,4]) 
print(np.cos(var2))  
print(np.sin(var2))             

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [ ]:
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])  
x = var.reshape(3,4,1) 
print(x)                                                                                                                                       

[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [2]:
import numpy as np 

In [20]:
variable = np.array([1,2,3,4,5,6,1,2,3,4]) 
x_1 = variable.reshape(2,5)  
print(x_1) 
print()
print(np.shape(x_1)) 
print()  

# Converts back to numpy 
x_2 = x_1.reshape(-1) 
print(x_2) 

[[1 2 3 4 5]
 [6 1 2 3 4]]

(2, 5)

[1 2 3 4 5 6 1 2 3 4]


### Broadcasting in Numpy

1. Check the rows and columns of the array
2. The columns of one of the arrays and columns of the other array must contain the number 1 

In [54]:
arr1 = np.array([14,12]) 

arr_1 = arr1.reshape(2,1)
print(arr_1)  
print("shape: " ,np.shape(arr_1))
print()

arr2 = np.array([1,2,3,4,5,6]) 

arr_2 = arr2.reshape(2,3) 
print(arr_2)
print("shape: " , np.shape(arr_2)) 
print() 
x1 = (arr_1 + arr_2)
print(x1)  



[[14]
 [12]]
shape:  (2, 1)

[[1 2 3]
 [4 5 6]]
shape:  (2, 3)

[[15 16 17]
 [16 17 18]]


### Indexing and Slicing

In [67]:
x = np.array([[[[1,2,3,4]]]])            
print(x[0,0,0,-3])             
print()              

y = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[3,2,1],[4,2,1],[5,6,3],[4,6,7]]])
print(y.ndim) 
print(y[0,-3,0:])
print() 


2

3
[4 5 6]



In [72]:
y = np.array([3,4,7,8,5,3,4]) 
print(y[:])

print(y[1:6])

print(y[::])

[3 4 7 8 5 3 4]
[4 7 8 5 3]
[3 4 7 8 5 3 4]


### Iteration 

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9]) 

for i in arr:
    print(i) 

1
2
3
4
5
6
7
8
9


In [76]:
var1 = np.array([[1,2,3,4],[5,6,7,8]])
print(var1)
print() 

for i in var1:
    print(i)

print() 

for j in var1:
    for k in j:
        print(k) 

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [82]:
var = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for i in var:
    print(i)

print()  


for j in var:
    for k in j:
        print(k)
print() 


for x in var:
    for y in x:
        for z in y:
            print(z) 

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]

1
2
3
4
5
6
7
8
9
10
11
12


In [87]:
var = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]) 
 
for i in np.nditer(var):
    print(i)
print() 

for i,d in np.ndenumerate(var):
     print(i , d) 

1
2
3
4
5
6
7
8
9
10
11
12

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
(2, 0, 0) 9
(2, 0, 1) 10
(2, 1, 0) 11
(2, 1, 1) 12


### Copy and Views

In [95]:
x1 = np.array([1,2,3,4,3,2,1])  
print("Actual: " , x1) 
print() 

x_copy = np.copy(x1) 
print("Copied: " , x_copy)
print()

x_view = x1.view() 
print(x_view) 

Actual:  [1 2 3 4 3 2 1]

Copied:  [1 2 3 4 3 2 1]

[1 2 3 4 3 2 1]


### Joining An Array 

1. Concatenate
2. Stack
3. Array Split

In [113]:
x = np.array([1,2,3,4,5,6,7,8,9,10]) 
y = np.array([12,13,14,15,16,11,22,23,24])

z = np.concatenate((x,y))  
print(z)


[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 11 22 23 24]


In [115]:
#2D Array
x_1 = np.array([[7,8],[9,10]])
x_2 = np.array([[19,18],[16,23]]) 

x_new = np.concatenate((x_1,x_2) , axis = 0)
x1_new = np.concatenate((x_1,x_2) , axis = 1)
print(x1_new)
print() 
print(x_new)  

[[ 7  8 19 18]
 [ 9 10 16 23]]

[[ 7  8]
 [ 9 10]
 [19 18]
 [16 23]]


In [ ]:
# stack

x_1 = np.array([1,2,3,4]) 
x_2 = np.array([8,7,6,5])

x_new = np.stack((x_1,x_2) , axis = 0)
print(x_new) 
print()

x1_new = np.vstack((x_1,x_2))              #vstack is along the column 
print(x1_new)
print() 

x2_new = np.dstack((x_1,x_2))              #dstack is along the height                             
print(x2_new) 
print() 

x3_new = np.hstack((x_1,x_2))              #hstack is along the row          
print(x3_new) 

[[1 2 3 4]
 [8 7 6 5]]

[[1 2 3 4]
 [8 7 6 5]]

[[[1 8]
  [2 7]
  [3 6]
  [4 5]]]

[1 2 3 4 8 7 6 5]


In [ ]:
x1 = np.array([1,2,3,4])
x2 = np.array([5,6,7,8]) 
                             
x3 =  np.array_split(x1,2) 
print(x3)                     

[array([1, 2]), array([3, 4])]


### Search

In [6]:
import numpy as np
var = np.array([1,2,3,4,5,3,2,1,3,6]) 
#index          0,1,2,3,4,5,6,7,8,9

x = np.where( (var%2) == 0 ) 

print(x) 

(array([1, 3, 6, 9]),)


In [31]:
var1 = np.array([1,2,3,4,5,6,8,9,10,11,12,13,14])
#                0,1,2,3,4,5,6,7,8,,,9,10,11,12
print(var1) 
x1 = np.searchsorted(x , 7 , side = "left") 

print(x1)  

[ 1  2  3  4  5  6  8  9 10 11 12 13 14]
5


### Sort

In [32]:
var_x = np.array([9,8,7,6,1,2,3,4,23,45,76,43,12,90]) 

print(np.sort(var_x)) 

[ 1  2  3  4  6  7  8  9 12 23 43 45 76 90]


### Filter Array

In [35]:
var_3 = np.array(["a" , "b" , "s" , "d" , "t"]) 

f = [True,False,False,True,False]

print(var_3)
print() 

new_a = var_3[f]

print(new_a)  

['a' 'b' 's' 'd' 't']

['a' 'd']


### Arithmetic Functions 

1. Shuffle
2. Unique
3. Resize
4. Flatten - order('C' , 'F' , 'A' , 'K') 
5. Ravel

In [39]:
#Shuffle
import numpy as np 

var = np.array([1,2,3,4,5,6,7,8,9]) 
np.random.shuffle(var) 

print(var) 


[1 8 4 3 6 5 7 9 2]


In [43]:
#Unique 
var1 = np.array([1,2,3,4,5,2,6,7]) 

x = np.unique(var1 , return_index=True , return_counts=True) 

print(x) 

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 6, 7]), array([1, 2, 1, 1, 1, 1, 1]))


In [46]:
#Resize
var2 = np.array([1,2,3,4,5,6,7,8]) 

y = np.resize(var2,(2,4))

print(y) 

[[1 2 3 4]
 [5 6 7 8]]


In [52]:
# Flatten - Converts higher dimension to one dimension 
x = np.array([1,2,3,4,5] , ndmin = 10)
print(x) 
print() 
print(x.flatten(order = "F")) 

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]

[1 2 3 4 5]


In [60]:
x = np.array([[1,2,3,4,5,6,7,8,9]])
print(x)
print()

y = np.resize(x , (3,3))
print(np.resize(x , (3,3)))
print() 

print(y.ravel(order = "C")) 

[[1 2 3 4 5 6 7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]


### Insert

In [65]:
import numpy as np

var = np.array([1,2,3,4]) 
print(var)
print() 

y = np.insert(var , (2,4) , 40)

print(y) 

[1 2 3 4]

[ 1  2 40  3  4 40]


In [79]:
var1 = np.array([[1,2,3],[4,5,6]]) 

v1 = np.insert(var1, 2 , [6,7,8] , axis = 0) 

print(v1) 

[[1 2 3]
 [4 5 6]
 [6 7 8]]


### Delete

In [80]:
import numpy as np 

var1 = np.array([1,2,3,4]) 

print(var1) 

d = np.delete(var1 , 2) 

print(d) 

[1 2 3 4]
[1 2 4]


### Matrix in Numpy

In [82]:
import numpy as np 

var = np.matrix([[1,2,3],[4,5,6]]) 

print(var) 
print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [87]:
var = np.matrix([[1,2,3],[4,5,6]])
var1 = np.matrix([[1,2,3],[4,5,6]])
print(var)
print("Shape: ", np.shape(var)) 
print()
print(var1)
print("Shape: ", np.shape(var1)) 
print() 
print(var+var1)
print("Shape: ", np.shape(var+var1)) 

[[1 2 3]
 [4 5 6]]
Shape:  (2, 3)

[[1 2 3]
 [4 5 6]]
Shape:  (2, 3)

[[ 2  4  6]
 [ 8 10 12]]
Shape:  (2, 3)


In [98]:
var = np.matrix([[1,2,3,4],[5,6,7,8]]) 
var1 = np.matrix([[9,10,11,12],[13,14,15,16]]) 

print(var)
print("Shape: ", np.shape(var)) 
print() 
print(var1)
print("Shape: ", np.shape(var1))
print() 

var2 = var1.reshape(4,2) 
print("Reshaped Array: ") 
print(var2) 
print("Shape: ", np.shape(var2)) 
print() 
print(var.dot(var2))
print("Shape: " , np.shape(var.dot(var2))) 

[[1 2 3 4]
 [5 6 7 8]]
Shape:  (2, 4)

[[ 9 10 11 12]
 [13 14 15 16]]
Shape:  (2, 4)

Reshaped Array: 
[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Shape:  (4, 2)

[[130 140]
 [322 348]]
Shape:  (2, 2)


#### Matrix Function 

1. Transpose
2. Swapaxes
3. Inverse
4. Power
5. Determinant

In [100]:
var1 = np.matrix([[1,2,3,4],
                  [5,6,7,8]])  
print(var1) 
print()            


[[1 2 3 4]
 [5 6 7 8]]



In [106]:
var = np.matrix([[1,2,3,4],[5,6,7,8]]) 
print(var) 
print() 

var1 = var.T   #same
print(var1)
print() 

var2 = np.transpose(var)  #same
print(var2) 


[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [115]:
x_1 = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(x_1)
print() 

x_2 = np.swapaxes(x_1 , 0 , 1)  
print(x_2) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [117]:
var_1 = np.matrix([[18,12,13,16],
                   [18,12,11,10],
                   [1,43,23,12],
                   [12,13,16,34]]) 
print(var_1) 
print()

var_2 = np.linalg.inv(var_1)  
print(var_2) 


[[18 12 13 16]
 [18 12 11 10]
 [ 1 43 23 12]
 [12 13 16 34]]

[[-0.28154535  0.30459294 -0.02172111  0.05057204]
 [-0.76521307  0.65412038  0.00397944  0.16630741]
 [ 1.64135301 -1.39114575  0.0447687  -0.37904162]
 [-0.380451    0.29704858 -0.0149229   0.12634721]]


In [126]:
var_1 = np.matrix([[1,2,3],
                   [4,5,6],
                   [7,8,10]])
print(var_1) 
print() 

print(np.linalg.matrix_power(var_1,-2))
print() 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

[[  2.33333333  -6.           3.        ]
 [ -4.          18.33333333 -10.        ]
 [  1.66666667 -10.66666667   6.        ]]



In [127]:
var1 = np.matrix([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(var1) 
print() 
var_1 = np.linalg.det(var1) 
print(var_1) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

0.0
